# Generated by Django 5.0.7 on 2024-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_video', models.FileField(upload_to='driving_videos/')),
                ('input_image', models.ImageField(upload_to='input_images/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output_animations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
